### ISSUE TITLE
Cannot launch

### ISSUE THREAD

**Issue by TypicalModMaker** [layou233/ZBProxy#138]
______  _____   _____   _____    _____  __    __ __    __
|___  / |  _  \ |  _  \ |  _  \  /  _  \ \ \  / / \ \  / /
   / /  | |_| | | |_| | | |_| |  | | | |  \ \/ /   \ \/ / 
  / /   |  _  { |  ___/ |  _  /  | | | |   }  {     \  /
 / /__  | |_| | | |     | | \ \  | |_| |  / /\ \    / /
/_____| |_____/ |_|     |_|  \_\ \_____/ /_/  \_\  /_/
Welcome to ZBProxy 3.1-alpha.1 (073a452)!
Build Information: go1.22.5, linux/amd64, CGO disabled
panic: open ZBProxy.json: no such file or directory

goroutine 1 [running]:
main.main()
        github.com/layou233/zbproxy/v3/cmd/zbproxy/main.go:37 +0x5fd

Running latest beta github action, fresh start without config so it fails but in readme.md its stated that it auto generates default config

**Comment by layou233** [comment]
I'm currently working on the next minor version (as you can see the `dev-next` branch), but the auto-generation feature was missed in that build. Sorry for the inconvenience.

Fixed in bb5f3b0. I have started an action build. Please download the latest build and try again.

The README may be out of date. The documentation is a better reference.

**Comment by TypicalModMaker** [comment]
Alright, works now
Thanks.
