### ISSUE TITLE
PreGame Checks

### ISSUE THREAD

**Issue by Ayush-Mann-0** [layou233/ZBProxy#145]
how can i make it so that it checks for player join once its in a world ( basically a duel game ) and then return the player uuid , i have never worked on a proxy or anything so i'm not so sure

**Comment by layou233** [comment]
Minecraft protocol encrypts all packets after the initial handshake, which makes it impossible for relay (like ZBProxy) to observe player status without MitM-like features. Because of that, we do not provide post-join features (like inform you when someone joined Skywars etc).

You may consider looking for some server public APIs to implement such features.

**Comment by Ayush-Mann-0** [comment]
oh thank you
